// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package add

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderAdder creates a new instance of MockOrderAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderAdder {
	mock := &MockOrderAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderAdder is an autogenerated mock type for the OrderAdder type
type MockOrderAdder struct {
	mock.Mock
}

type MockOrderAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderAdder) EXPECT() *MockOrderAdder_Expecter {
	return &MockOrderAdder_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function for the type MockOrderAdder
func (_mock *MockOrderAdder) AddOrder(ctx context.Context, orderNum string, login string) error {
	ret := _mock.Called(ctx, orderNum, login)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderNum, login)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderAdder_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type MockOrderAdder_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
//   - login string
func (_e *MockOrderAdder_Expecter) AddOrder(ctx interface{}, orderNum interface{}, login interface{}) *MockOrderAdder_AddOrder_Call {
	return &MockOrderAdder_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, orderNum, login)}
}

func (_c *MockOrderAdder_AddOrder_Call) Run(run func(ctx context.Context, orderNum string, login string)) *MockOrderAdder_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderAdder_AddOrder_Call) Return(err error) *MockOrderAdder_AddOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderAdder_AddOrder_Call) RunAndReturn(run func(ctx context.Context, orderNum string, login string) error) *MockOrderAdder_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}
